const shared = require('../services/shared.service');

module.exports = {
  prepareRequestContext: shared.prepareRequestContext,
  getDashboardData: (ctx, options) => shared.getDashboardData(ctx, options),
  getUserScope: shared.getUserScope,
  getChildProgressRecords: shared.getChildProgressRecords,
  getCheckins: shared.getCheckins,
  getPlanDayIndexForDate: shared.getPlanDayIndexForDate,
  getNextPlanDayIndexForDate: shared.getNextPlanDayIndexForDate,
  buildPlanForDay: shared.buildPlanForDay,
  getPeppaReviewCursor: shared.getPeppaReviewCursor,
  getPeppaReviewPlanOptions: shared.getPeppaReviewPlanOptions,
  decoratePlannedTasks: shared.decoratePlannedTasks,
  decoratePlanTasks: shared.decoratePlanTasks,
  resolveStandaloneCategoryTasks: shared.resolveStandaloneCategoryTasks,
  buildCategorySummary: shared.buildCategorySummary,
  getPlanCatalog: shared.getPlanCatalog,
  getCatalog: shared.getCatalog,
  getCategoryLabel: shared.getCategoryLabel,
  addDays: shared.addDays,
  getTodayString: shared.getTodayString,
  buildLevelCatalogEntry: shared.buildLevelCatalogEntry,
  buildEmptyProgress: shared.buildEmptyProgress,
  decorateTask: shared.decorateTask,
  getTranscriptBundle: shared.getTranscriptBundle,
  upsertDailyReport: shared.upsertDailyReport,
  buildCatchupState: shared.buildCatchupState,
  getPlanStartDate: shared.getPlanStartDate,
  normalizeStudyRole: shared.normalizeStudyRole,
  isStudyWriteAllowed: shared.isStudyWriteAllowed,
  maybeCreateCheckin: shared.maybeCreateCheckin,
  reconcileCheckins: shared.reconcileCheckins,
  saveProgressRecord: shared.saveProgressRecord,
  getResourceDebugSnapshot: shared.getResourceDebugSnapshot,
  level: shared.level
};
