const shared = require('../services/shared.service');

module.exports = {
  prepareRequestContext: shared.prepareRequestContext,
  getDashboardData: (ctx, options) => shared.getDashboardData(ctx, options),
  getCumulativeListeningMinutes: (scope) => shared.getCumulativeListeningMinutes(scope),
  getUserScope: shared.getUserScope,
  getChildProgressRecords: shared.getChildProgressRecords,
  getChildProgressRecordsByDate: shared.getChildProgressRecordsByDate,
  getCheckins: shared.getCheckins,
  getActiveListeningPlan: shared.getActiveListeningPlan,
  getActiveListeningPlanByScope: shared.getActiveListeningPlanByScope,
  saveListeningPlanMaterial: shared.saveListeningPlanMaterial,
  removeListeningPlanMaterial: shared.removeListeningPlanMaterial,
  buildListeningPlanMaterials: shared.buildListeningPlanMaterials,
  getCatalogSummary: shared.getCatalogSummary,
  getCustomPlanDayIndex: shared.getCustomPlanDayIndex,
  buildListeningPlanForDay: shared.buildListeningPlanForDay,
  decorateListeningPlanTasks: shared.decorateListeningPlanTasks,
  getCompletionItemsByDate: shared.getCompletionItemsByDate,
  getPlanDayIndexForDate: shared.getPlanDayIndexForDate,
  getNextPlanDayIndexForDate: shared.getNextPlanDayIndexForDate,
  buildPlanForDay: shared.buildPlanForDay,
  buildFixedPlanBySlots: shared.buildFixedPlanBySlots,
  decorateFixedSlotPlanTasks: shared.decorateFixedSlotPlanTasks,
  getPeppaReviewCursor: shared.getPeppaReviewCursor,
  getPeppaReviewPlanOptions: shared.getPeppaReviewPlanOptions,
  decoratePlannedTasks: shared.decoratePlannedTasks,
  decoratePlanTasks: shared.decoratePlanTasks,
  resolveStandaloneCategoryTasks: shared.resolveStandaloneCategoryTasks,
  buildCategorySummary: shared.buildCategorySummary,
  getPlanCatalog: shared.getPlanCatalog,
  getCatalog: shared.getCatalog,
  getCategoryLabel: shared.getCategoryLabel,
  addDays: shared.addDays,
  getTodayString: shared.getTodayString,
  buildLevelCatalogEntry: shared.buildLevelCatalogEntry,
  buildEmptyProgress: shared.buildEmptyProgress,
  decorateTask: shared.decorateTask,
  getTranscriptBundle: shared.getTranscriptBundle,
  upsertDailyReport: shared.upsertDailyReport,
  buildCatchupState: shared.buildCatchupState,
  getPlanStartDate: shared.getPlanStartDate,
  normalizeStudyRole: shared.normalizeStudyRole,
  isStudyWriteAllowed: shared.isStudyWriteAllowed,
  maybeCreateCheckin: shared.maybeCreateCheckin,
  reconcileCheckins: shared.reconcileCheckins,
  saveProgressRecord: shared.saveProgressRecord,
  syncFixedPlanProgressSummary: shared.syncFixedPlanProgressSummary,
  getResourceDebugSnapshot: shared.getResourceDebugSnapshot,
  isYoyoChild: shared.isYoyoChild,
  level: shared.level
};
