const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const servicePath = path.join(__dirname, '..', 'services', 'catalog.service.js');
const source = fs.readFileSync(servicePath, 'utf8');
const indexSource = fs.readFileSync(path.join(__dirname, '..', 'index.js'), 'utf8');
const storeSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'utils', 'store.js'), 'utf8');
const materialPageSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'pages', 'material', 'index.js'), 'utf8');
const directory = require('../data/material-directory.json');

test('听力与写作目录使用轻量摘要且详情优先按 id 读取单条文件', () => {
  assert.match(source, /loadBundledMaterialIndex\(\)/);
  assert.match(source, /loadMaterialItem\(moduleId, itemId\)/);
  assert.match(source, /downloadMaterialItemJson/);
  assert.match(source, /items-v1/);
  assert.match(source, /ieltsMaterialItemDirectories/);
  assert.match(source, /const root = `_content\/ielts-academic\/cambridge-\$\{book\}`/);
  assert.match(source, /\$\{root\}\/listening\/items-v2/);
  assert.match(source, /\$\{root\}\/writing\/items-v3/);
  assert.doesNotMatch(source.split('\n').slice(0, 5).join('\n'), /shared\.service|storage\.adapter/);
  assert.match(indexSource, /'getMaterialIndex'/);
  assert.equal(directory.listeningEm1.length, 67);
  assert.equal(directory.listeningEm2.length, 76);
  assert.equal(directory.writingEm1.length, 159);
  assert.equal(directory.writingEm2.length, 181);
  assert.equal(directory.listeningSeniorSpring.length, 9);
  assert.equal(directory.listeningSeniorAutumn.length, 15);
  assert.equal(directory.writingSeniorSpring.length, 30);
  assert.deepEqual(directory.writingSeniorSpring.filter((item) => item.year === 2022).map((item) => item.contentType), ['summary-writing', 'translation', 'guided-writing']);
  assert.deepEqual(directory.writingSeniorSpring.filter((item) => item.year === 2023).map((item) => item.contentType), ['summary-writing', 'translation', 'guided-writing']);
  assert.equal(directory.writingSeniorAutumn.length, 41);
  assert.equal(directory.writingSeniorAutumn[0].contentType, 'translation');
  assert.equal(directory.writingSeniorAutumn[0].questionCount, 6);
  assert.equal(Object.hasOwn(directory.writingSeniorAutumn[0], 'questions'), false);
  assert.equal(Object.hasOwn(directory.listeningEm2[0], 'questions'), false);
  assert.equal(Object.hasOwn(directory.writingEm2[0], 'prompt'), false);
  assert.equal(directory.writingIelts.length, 96);
  assert.equal(directory.listeningIelts.length, 48);
  assert.equal(directory.speakingIelts.length, 48);
  assert.match(storeSource, /catalogVersion: 'ielts-academic-10-21-v1'/);
  assert.match(materialPageSource, /materialHomeSnapshotV6/);
  assert.match(materialPageSource, /buildIeltsExams/);
  assert.match(materialPageSource, /MATERIAL_CATALOG_VERSION/);
  assert.equal(directory.listeningSeniorAutumn[0].durationSec, 906.71);
});
